### ISSUE TITLE
Problem statement review

### ISSUE THREAD

**Issue by PeaWagon** [PeaWagon/Kaplan#1]
My problem statement document is located in docs/ProblemStatement/ProblemStatement.pdf (or tex). Please let me know if I should be raising this issue on the cas741 gitlab webpage instead. Instructions state to chose the group's repository. I wasn't quite sure if that was the course repo or not (no one else seems to have made an issue there for their problem statements). 

Thanks,
Jen

**Comment by smiths** [comment]
This is the right place for your issue.  I'll have a look at your problem statement soon.

**Comment by smiths** [comment]
@PeaWagon you commented out `%\input{../Comments}` from your `Proposal.tex` file.  Can you please uncomment it and add the Comments.tex file under version control.  That way I can add comments directly to your tex file.

**Comment by smiths** [comment]
Some comments on your proposal:

- what is a smiles string?
- rather than say evolutionary algorithm, it would be better to be more abstract.  You are doing an optimization, so you should say that.  You can still list the example of an evolutionary algorithm, but you don't want to lock yourself into that too early
- will people outside of your research group be able to run your software?  I'm specifically wondering about me and, to some extent, your classmates.  Specific concerns follow:
  * Can there be a serial version, or will running it require parallel computation?
  * What if Vetee isn't working in time for this course?
  * Who has access to Gaussian?
  * Will your software be difficult to install, compile?

**Comment by PeaWagon** [comment]
Okay so I should have covered most of these questions in the problem statement. More specifically: 
SMILES = Simplified molecular-input line-entry system
Parallelization would be a nice feature to add, but it is not a priority. I expect to write serial code first.
Vetee and Gaussian will not be necessary for the project to work, I just need to leave places where they can be easily connected for later. I will need a way to evaluate molecular energies - there should be a few open-source packages for this purpose. Gaussian can compute the energies; it is accessible to anyone who has a Compute Canada/Sharcnet account, but purchasing a personal license is very expensive. I will leave the choice of energy computation up to the user. 
I will try to make the project into an anaconda package - it can also be fairly easily installed using pip (development option -e).

**Comment by smiths** [comment]
Thank you for the clarification @PeaWagon.  I can see that you added SMILES in e5e856f16e6b200574ae0d1c8baad1a657970f82.  In the future, it helps if you link to the commit that closes the issue.

I approve your problem statement, and by extension ,  your project.
