### ISSUE TITLE
SysVnVPlan SRS Verification Plan issue

### ISSUE THREAD

**Issue by vajihehm** [PeaWagon/Kaplan#17]
@PeaWagon In the section SRS Verification Plan, there are a lot of the information and questions in your mind relating to the Likely Changes. I think in this section these questions are not required because for me as a reviewer these questions led a considerable confusion.

**Comment by PeaWagon** [comment]
My supervisor has made some comments with regards to my testing plan. Since he can provide feedback about the science, I imagine my SRS must change. If I had known all of the science and assumptions, then the SRS would have been written properly (with the correct assumptions in mind). Then, I wouldn't have needed to include any discussion of the likely changes. I'm sorry that my comments were confusing - I think they were just intended for a different audience (and I have a tendency to ramble when I don't understand something completely :smiley:). Perhaps when I write my vnv report my intentions will become clearer.
