### ISSUE TITLE
Module Guide feedback #2

### ISSUE THREAD

**Issue by oluowoj** [PeaWagon/Kaplan#29]
@PeaWagon, AC8 made me a bit curious, if the programming language is a likely change, this impacts most of the modules I assume, if not all, which contradicts this statement in the screenshot below or maybe I am wrong.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/43192745/48235495-1f9b5400-e38c-11e8-8690-7a23e2a602d2.png">

I am looking at this from my own project point of view as well and want to understand more...how changing the programming language impacts the design and should this be in the AC list?
 
Maybe @smiths has some opinion about this.

**Comment by PeaWagon** [comment]
@smiths comment was:
There seems to be some misunderstanding about the anticipated changes.
  These are what become the secrets of your modules.  The interface to your
  modules will be abstract so that you can hide the anticipated changes in one
  module.  Changing programming language is not something you can ``hide'' in
  one module.  It would mean changing all of your modules.

So I took this out from the list of anticipated changes. Professor Smith also noted that it might be better to make my documentation language agnostic such that Kaplan can be re-written in another programming language without much difficulty. As it is, my program is pretty much only suited for python. Mostly my concern for rewriting my code is coming from my expectation that it will run very slowly. In any case, the code will need profiling and proper testing and verification before I can start changing the programming language - this anticipated change is a long way away from being realised.
