### ISSUE TITLE
Module Guide feedback #3

### ISSUE THREAD

**Issue by oluowoj** [PeaWagon/Kaplan#30]
I think M5 and M6 should somehow be linked to one or more of your functional requirements. Please disregard this feedback if its not the case.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/43192745/48236025-68540c80-e38e-11e8-840d-57cac81f456e.png">

Great job Jenn, well documented!

**Comment by PeaWagon** [comment]
Hey @oluowoj thanks for this feedback. I think I am actually missing a requirement in my SRS that should state the program needs to optimise the geometries, which is why the tournament module is not referenced here (since it would map to a non-existent requirement). I will add a new requirement in my SRS and reference it here.

As for module 5, this should be in R2 and R3. I will add this in a future commit.

**Comment by PeaWagon** [comment]
Done 25a6e6a
