### ISSUE TITLE
SRS Tables of Symbols/Acronyms missing and unnecessary entries

### ISSUE THREAD

**Issue by bmaclach** [PeaWagon/Kaplan#6]
I noticed some symbols and acronyms that were used in the body of the SRS but not defined in the Table of Symbols or Table of Acronyms.

**Missing from Table of Symbols**
- α
- β
- _c<sub>i</sub>_
- _c_ (This one and the above one are both used in the text following T1, though they seem to refer to two different things. If this is correct, the symbol _c_ should not be used for both of them)
- _k_ (used in GD1 and in the text below T1, each time representing something different. _k_ should only be used for one of these, and the other should be replaced with a new symbol (otherwise it is ambiguous)
- ζ
- _G<sub>n</sub>_ (I believe this is the same as _n<sub>G</sub>_, which does appear in the table, so maybe all instances of _G<sub>n</sub>_ in the body should be replaced by _n<sub>G</sub>_)
- _Z<sub>α</sub>_
- _j_ (used as an index for a conformer along with _i_. Maybe give _i_ and _j_ each their own entry in the table of symbols? If you do this, the _E<sub>i</sub>_ entry should be removed as it is already covered by _E_ and _i_)
- _x_
- _y_
- _z_
- I would argue that the constants which appear in the Table of Units belong instead in the Table of Symbols

**Missing from Table of Acronyms**
- VSEPR
- VB
- 3D

I also found a couple entries that were not necessary in these tables:

- _G<sub>i</sub>_ is not used anywhere in the body of the SRS as far as I can tell, so it should not appear in the table
- Since you refer to your program as "Kaplan", which is neither an acronym or abbreviation (I think), it does not need to appear in the Table of Acronyms

**Comment by PeaWagon** [comment]
α and β are given in the symbol for spin (σ). They are also explained directly where they are used (and are only used once). If these symbols become more prevalent in my documentation, then I will add them as individual entries. 

As for c and c<sub>i</sub>, I changed c to c<sub>N</sub>. Again, these constants are not really key to understanding my program; they are used as general simplifications (hiding details). I actually need my supervisor to read this section to make sure my simplifications are correct (and meaningful). I will probably have to overhaul the whole T1 section. I'm not sure what the units will be yet (I will have to figure this out).

I have removed the k from T1; it isn't a necessary variable. I have added an entry to the table specifying i, j, and k as indexing variables. I don't think it matters for what, as I specify the indexing in the text where they are used.

x,y,z are similarly vague - they are used as coordinates for atoms and electrons. I changed it to upper case for electrons and lower case for atoms (since I will be using atoms more pretty much exclusively). I won't be manipulating the electronic coordinates since I won't be handling basis sets directly (handled by external program).

I'm keeping G<sub>i</sub> for now. I may want to use it in my other documentation.

I made a new table for numerical constants since they didn't seem to fit in either of the other tables.

Fixed in commit 8dc7d0ff27d7add57d1e729808d1a3500c0022d7
